name: unit-tests
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        perl: [ '5.32', '5.30', '5.28' ]
        year: [2019, 2020, 2021]
    name: Year ${{ matrix.year }}; Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1.14.1
        install-modules: |
          Statistics::Descriptive
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - run: cd ${{ matrix.year }} && cpanm --installdeps .
      - run: cd ${{ matrix.year }} && prove -lv t

