name: unit-tests
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        perl: [ '5.32' ]
        year: [2022, 2021, 2020, 2019]
    name: Year ${{ matrix.year }}; Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1.14.1
        with:
          perl-version: ${{ matrix.perl }}
          install-modules: |
            Statistics::Descriptive
      - run: perl -V
      - run: cd ${{ matrix.year }} && cpanm --installdeps .
      - run: cd ${{ matrix.year }} && prove -lv t

